spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/healthtogether
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    #    database: mysql
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false

  # 콘솔 확인 을 위한 always
  output:
    ansi:
      enabled: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
# 파라미터 확인을 위한 trace
#logging:
#  level:
#    org.hibernate.type: trace